# @package algorithm

learning_rate:       1e-3
num_envs:            1
num_eval_envs:       10
buffer_size:         10_000
gamma:               0.99
target_network_frequency: 4
batch_size:          32

update_hidden_state: false

start_e:             1.0
end_e:               0.05
exploration_fraction: 0.5

learning_starts:     100
train_frequency:     1

