# @package algorithm
batch_size: 128
buffer_size: 100000
gamma: 0.99
learning_rate: 0.00001142092212788148
learning_starts: 50000
sample_sequence_length: 4
tau: 1
start_e: 1
end_e: 0.05
exploration_fraction: 0.5
target_network_frequency: 1000
train_frequency: 10
update_hidden_state: false
