# @package _global_

total_timesteps: 10_000_000

algorithm: 
  learning_rate: 3e-4
  batch_size: 64


  tau: 0.995

  start_e: 1.0
  end_e: 0.1428
  exploration_fraction: 0.1

  feature_extractor:
    features: [256, 256]

