_target_: memory_rl.networks.CNN
layers:
  module:
    _target_: flax.linen.Conv
    features: 16
    kernel_size: [3, 3]
    strides: [1, 1]
    padding: "VALID"
    use_bias: false
  activation:
    _target_: flax.linen.relu
