from typing import Any, Protocol


class Logger(Protocol):
    def init(self, config: dict[str, Any]) -> Any: ...
    def log(self, state: Any, data: dict[str, Any], *, step: int) -> Any: ...
    def emit(self, state: Any) -> Any: ...
    def finish(self, state: Any) -> None: ...        
