_target_: memory_rl.networks.SeperateFeatureExtractor

observation_extractor:
  _target_: memory_rl.networks.MLP
  features: [64]
action_extractor:
  _target_: memory_rl.networks.MLP
  features: [32]
reward_extractor: null
done_extractor: null

