learning_rate: 2e-4
num_envs: 1024
num_eval_envs: 2
num_steps: 64
anneal_lr: True
gae_lambda: 0.8
num_minibatches: 8
update_epochs: 4
normalize_advantage: True
clip_coef: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 1.0

actor:
  feature_extractor:
    extractor:
      features: [512]
      kernel_init: 
        _target_: flax.linen.initializers.orthogonal
        scale: 1.414
  torso:
    features: [512, 512, 512]
    kernel_init: 
      _target_: flax.linen.initializers.orthogonal
      scale: 1.414

critic:
  feature_extractor:
    extractor:
      features: [512]
      kernel_init: 
        _target_: flax.linen.initializers.orthogonal
        scale: 1.414
  torso:
    features: [512, 512, 512]
    kernel_init:
      _target_: flax.linen.initializers.orthogonal
      scale: 1.414
