_target_: memory_rl.environments.gymnax.make
env_id: MemoryChain-bsuite

wrappers:
 - _target_: memory_rl.utils.wrapper.BSuiteWrapper


parameters:
  memory_length: 5
  max_steps_in_episode: ${eval:${.memory_length}+1}

