defaults:
  - feature_extractor: shared
  - torso: mlp

name: pqn
learning_rate:       1e-4
num_envs:            1024
num_eval_envs:       4
num_steps:           32
num_minibatches:     4
update_epochs:       4
td_lambda:           0.7
gamma:               0.99
batch_size:          64

start_e:             0.5
end_e:               0.005
exploration_fraction: 0.2

learning_starts:     0

feature_extractor:
  extractor:
    features:        [128]
    normalizer:
      _target_: flax.linen.LayerNorm
torso:
  features:        [128]
  normalizer:
    _target_: flax.linen.LayerNorm
