# Algorithm specific arguments
name: rppo
learning_rate: 0.0003
num_envs: 512
num_steps: 64
anneal_lr: False
gamma: 0.99
gae_lambda: 0.5
num_minibatches: 64
update_epochs: 5
norm_adv: False
clip_coef: 0.2
clip_vloss: False
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
learning_starts: 0
hidden_dims: [256]
actor_cell_size: 256
critic_cell_size: 256
