name: rppo
learning_rate: 3e-4
num_envs: 64
num_eval_envs: 64
num_steps: 64
anneal_lr: False
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 8
update_epochs: 8
normalize_advantage: True
clip_coef: 0.2
clip_vloss: False
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
learning_starts: 0
actor:
  feature_extractor:
    _target_: memory_rl.networks.feature_extractors.MLP
    features: [256]
  cell: 
    _target_: memory_rl.networks.recurrent.MaskedGRUCell
    features: 256
critic: 
  feature_extractor:
    _target_: memory_rl.networks.feature_extractors.MLP
    features: [256]
  cell:
    _target_: memory_rl.networks.recurrent.MaskedGRUCell
    features: 256
