defaults:
  - feature_extractor@actor.feature_extractor: shared
  - torso@actor.torso: gtrxl
    
  - feature_extractor@critic.feature_extractor: shared
  - torso@critic.torso: gtrxl

  - mode: TBPTT


name: rppo
learning_rate: 3e-4
num_envs: 32
num_eval_envs: 16
# num_steps: controlled via mode.length instead
anneal_lr: True
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 4
normalize_advantage: True
clip_coef: 0.2
clip_vloss: True
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
learning_starts: 0

actor:
  feature_extractor:
    extractor:
      kernel_init:
        _target_: flax.linen.initializers.orthogonal
        scale: 1.414
  torso:
    kernel_init: 
      _target_: flax.linen.initializers.orthogonal
      scale: 1.414
critic: 
  feature_extractor:
    extractor: 
      kernel_init:
        _target_: flax.linen.initializers.orthogonal
        scale: 1.414
