defaults:
  - /network/feature_extractor@actor.feature_extractor: mlp
  - /network/torso@actor.torso: gru
    
  - /network/feature_extractor@critic.feature_extractor: mlp
  - /network/torso@critic.torso: gru

name: rppo
learning_rate: 3e-4
num_envs: 64
num_eval_envs: 64
num_steps: 64
anneal_lr: False
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 8
update_epochs: 8
normalize_advantage: True
clip_coef: 0.2
clip_vloss: False
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
learning_starts: 0

actor:
  feature_extractor:
    kernel_init:
      _target_: flax.linen.initializers.orthogonal
      scale: 1.414
critic: 
  feature_extractor:
    kernel_init:
      _target_: flax.linen.initializers.orthogonal
      scale: 1.414
