defaults:
  - /network/feature_extractor@actor.feature_extractor: mlp
  - /network/torso@actor.torso: gru
    
  - /network/feature_extractor@critic.feature_extractor: mlp
  - /network/torso@critic.torso: gru

name: rppo
learning_rate: 2.5e-4
num_envs: 4
num_eval_envs: 4
num_steps: 128
anneal_lr: True
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 4
normalize_advantage: True
clip_coef: 0.2
clip_vloss: False
ent_coef: 0.001
vf_coef: 0.5
max_grad_norm: 0.5
learning_starts: 0

actor:
  feature_extractor:
    kernel_init:
      _target_: flax.linen.initializers.orthogonal
      scale: 1.414
  torso:
    kernel_init: 
      _target_: flax.linen.initializers.orthogonal
      scale: 1.414
critic: 
  feature_extractor:
    kernel_init:
      _target_: flax.linen.initializers.orthogonal
      scale: 1.414
