defaults:
  - /network/feature_extractor@actor.feature_extractor: mlp
  - /network/torso@actor.torso: gru

  - /network/feature_extractor@critic.feature_extractor: mlp
  - /network/torso@critic.torso: gru
  - /mode: TBPTT

name: rsac
policy_lr:            3e-4
q_lr:           3e-4
temp_lr:             3e-4
num_envs:            10
num_eval_envs:       10
buffer_size:         100_000
gamma:               0.99
tau:                 5e-3
train_frequency:     10
target_update_frequency: 1
batch_size:          256
init_temperature:    1.0
target_entropy_multiplier: 1.0
max_action:          1.0
backup_entropy:      false
learning_starts:     5_000

