defaults:
  - /network/feature_extractor@actor.feature_extractor: mlp
  - /network/torso@actor.torso: gru

  - /network/feature_extractor@critic.feature_extractor: mlp
  - /network/torso@critic.torso: gru

  - /mode: TBPTT

name: rsacd
policy_lr:            3e-4
q_lr:           3e-4
temp_lr:             3e-4
num_envs:            10
num_eval_envs:       10
buffer_size:         10_000
gamma:               0.99
tau:                 5e-3
train_frequency:     10
target_update_frequency: 10
batch_size:          128
backup_entropy:      False
init_temperature:    1.0
policy_final_fc_init_scale: 1e-3
target_entropy_multiplier: 0.5
learning_starts:     10_000
