defaults:
  - feature_extractor@actor.feature_extractor: shared
  - torso@actor.torso: gru

  - feature_extractor@critic.feature_extractor: shared
  - torso@critic.torso: gru
  - mode: BPTT
  - buffer: episode_buffer

name: rsacd
actor_lr:            3e-4
critic_lr:           3e-4
alpha_lr:             3e-4
num_envs:            10
num_eval_envs:       10
buffer_size:         10_000
gamma:               0.99
tau:                 5e-3
train_frequency:     10
target_update_frequency: 10
batch_size:          128
initial_alpha:    0.1
target_entropy_scale: 0.98
learning_starts:     10_000
