defaults:
  - feature_extractor@actor.feature_extractor: shared
  - torso@actor.torso: gru

  - feature_extractor@critic.feature_extractor: shared
  - torso@critic.torso: gru
  - mode: BPTT
  - buffer: episode_buffer

name: rsacd
policy_lr:            3e-4
q_lr:           3e-4
temp_lr:             3e-4
num_envs:            10
num_eval_envs:       10
buffer_size:         10_000
gamma:               0.99
tau:                 5e-3
train_frequency:     10
target_update_frequency: 10
batch_size:          128
backup_entropy:      False
init_temperature:    0.1
policy_final_fc_init_scale: 1e-3
target_entropy_scale: 0.98
learning_starts:     10_000
