defaults:
  - /network/feature_extractor@actor.feature_extractor: mlp
  - /network/torso@actor.torso: mlp

  - /network/feature_extractor@critic.feature_extractor: mlp
  - /network/torso@critic.torso: mlp

name: sac
policy_lr:            3e-4
q_lr:           3e-4
temp_lr:             3e-4
num_envs:            5
num_eval_envs:       5
buffer_size:         100_000
gamma:               0.99
tau:                 5e-3
train_frequency:     5
target_update_frequency: 1
batch_size:          256
init_temperature:    1.0
policy_log_std_min: -10.0
policy_log_std_max: 2.0
policy_final_fc_init_scale: 1e-3
target_entropy_multiplier: 1.0
max_action:          1.0
backup_entropy:      false
learning_starts:     5_000
