defaults:
  - feature_extractor@actor.feature_extractor: shared
  - torso@actor.torso: mlp

  - feature_extractor@critic.feature_extractor: shared
  - torso@critic.torso: mlp

  - buffer: flat_buffer

name: sacd
actor_lr:           3e-4
critic_lr:                3e-4
alpha_lr:             3e-4
num_envs:            10
num_eval_envs:       10
buffer_size:         10_000
gamma:               0.99
tau:                 0.005
train_frequency:     10
target_update_frequency: 10
batch_size:          128
initial_alpha:    0.1
target_entropy_scale: 0.98
learning_starts:     10_000

max_grad_norm:       5
