defaults:
  - feature_extractor: shared
  - torso: mlp

name: soft_pqn
learning_rate:       1e-4
alpha_lr:            1e-4
beta_lr:             1e-4
initial_alpha:       1.0
initial_beta:        0.0
kl_target:           0.1
num_envs:            4
num_eval_envs:       10
num_steps:           32
num_minibatches:     4
update_epochs:       4
td_lambda:           0.7
gamma:               0.99
batch_size:          64

max_grad_norm:       0.5

learning_starts:     0

feature_extractor:
  extractor:
    features:        [128]
    normalizer:
      _target_: flax.linen.LayerNorm
torso:
  features:        [128]
  normalizer:
    _target_: flax.linen.LayerNorm
