# @package _global_

total_timesteps: 1_000_000_000
num_train_steps: 1_000_000
evaluate_every: 10_000_000

algorithm:
        learning_rate: 2e-4
        num_envs: 1024
        num_eval_envs: 2
        anneal_lr: True
        gae_lambda: 0.8
        num_minibatches: 8
        update_epochs: 4
        normalize_advantage: True
        clip_coef: 0.2
        ent_coef: 0.01
        vf_coef: 0.5
        max_grad_norm: 1.0

        mode:
          length: 64

        actor:
          feature_extractor:
            extractor:
              features: [256, 256]
              kernel_init: 
                _target_: flax.linen.initializers.orthogonal
                scale: 1.414
          torso:
            features: 256
            kernel_init: 
              _target_: flax.linen.initializers.orthogonal
              scale: 1.414

        critic:
          feature_extractor:
            extractor:
              features: [256, 256]
              kernel_init: 
                _target_: flax.linen.initializers.orthogonal
                scale: 1.414
          torso:
            features: 256
            kernel_init:
              _target_: flax.linen.initializers.orthogonal
              scale: 1.414

