# @package _global_

total_timesteps: 15_000_000

algorithm:
  learning_rate: 5e-5
  num_envs: 64
  num_eval_envs: 16
  anneal_lr: True
  gamma: 0.99
  gae_lambda: 1.0
  num_minibatches: 8
  update_epochs: 30
  normalize_advantage: True
  clip_coef: 0.2
  clip_vloss: True
  ent_coef: 0.0
  vf_coef: 1.0
  max_grad_norm: 0.5

