# @package _global_

total_timesteps: 1_000_000_000
num_train_steps: 100_000
evaluate_every: 1_000_000

algorithm:
  learning_rate:       1e-4
  num_envs:            1024
  num_eval_envs:       1
  num_steps:           128
  num_minibatches:     4
  update_epochs:       4
  td_lambda:           0.5
  gamma:               0.99
  max_grad_norm:       1.0

  learning_starts:     0

  feature_extractor:
    extractor:
      features:        [512]
      normalizer:
        _target_: flax.linen.LayerNorm
  torso:
    features: [512, 512]
    normalizer:
      _target_: flax.linen.LayerNorm
