_target_: memory_rl.buffers.make_episode_buffer
max_length: ${algorithm.buffer_size}
min_length: ${algorithm.batch_size}
sample_batch_size: ${algorithm.batch_size}
add_batch_size: ${algorithm.num_envs}
add_sequences: True
