# @package logger.loggers.console
_target_: memory_rl.loggers.ConsoleLogger
title: Memory RL
name: ${algorithm.name}
total_timesteps: ${total_timesteps}
refresh_per_second: 1
env_id: ${environment.env_id}
